# Generated by Django 2.2.7 on 2020-11-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Span',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('pos', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MadLib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('spans', models.ManyToManyField(to='main.Span')),
            ],
        ),
    ]
