# Generated by Django 2.2.7 on 2020-11-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_madlib_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='span',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
